### ISSUE TITLE
New Tyre label requirements from May 2021

### ISSUE THREAD

**Issue by aclDeveloper** [Arkq/eu-tire-label#1]
Effective May 2021 a new version of the tyre label will be mandatory.

References: 
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32020R0740
https://ec.europa.eu/info/energy-climate-change-environment/standards-tools-and-labels/products-labelling-rules-and-requirements/energy-label-and-ecodesign/energy-efficient-products/tyres_en

Are there any plans of implementing the required changes?

**Comment by arkq** [comment]
I've got no plans of updating it (to be honest I was not aware that there will be a new label requirement). I've been not using it since the time I've created it. But since someone is still using this project (I was not aware of that as well) I might try to update it with the new spec - it should not be hard (the hardest part is to get SVG file with all pictograms and texts).

**Comment by arkq** [comment]
I've updated the code a little bit, now it can generate EU/2020/740 labels as well. It's not finished yet (it misses ~tire pictograms, and~ QR-code), but current version might be use as a beta for integration testing.

Usage (it will show all EU/2020/740 pictograms):
```sh
eu-tire-label --tire-class=1 --fuel-efficiency=B --wet-grip=E --rolling-noise=1 --rolling-noise-db=72 \
    --trademark=MICHELINE --tire-size="P215/65 R15" --tire-type=WINTER --ice-grip --snow-grip >tire-label.svg
```

Example (few fixes will be required):
![tire-label](https://user-images.githubusercontent.com/6979798/114269006-a2fd7b80-9a04-11eb-8fe2-9846704c3688.png)

EDIT:
I've got one question though. Do you know where the QR-code link should point to? I'd like to see some real example how this EPREL database link should look like.

**Comment by arkq** [comment]
I've just pushed update which should cover EU/2020/740 regulation. I'm closing this issue. If you spot any errors, please do not hesitate to open a separate issue.
