### ISSUE TITLE
QR code generator issue --eprel-url flag only accepts incorrect URL

### ISSUE THREAD

**Issue by samholguin** [Arkq/eu-tire-label#2]
Love the library, big help.

We are struggling to make it work with a --eprel-url value that doesn't follow the pattern http://eprel.eu and these are incorrect URLs, they redirect to an eCommerce website.

The correct URLs to use are https://eprel.ec.europa.eu/screen/product/tyres/{tyre-id}

Are we missing something?

Thank you

**Comment by arkq** [comment]
I've just tested with `eu-tire-label -U https://eprel.ec.europa.eu/screen/product/tyres/2222 -C 1` and it seems that the QRcode was correctly generated (I've used this site to decode it: https://zxing.org/w/decode.jspx).
![snapshot-20211124-213942](https://user-images.githubusercontent.com/6979798/143310154-2937bd44-4aac-49c7-a71e-042354005d2c.png)

In fact, in the `--eprel-url` you can whatever URL you like up to 63 bytes in length.

**Comment by samholguin** [comment]
Ah, interesting, it must be an error on my side.

Thanks Arkq
